main:
  dataset_url: sqlite:////tmp/ingestify-demo/dataset.db
  file_url: file:///tmp/ingestify-demo/data/
  default_bucket: main

sources:
  statsbomb:
    type: sources.StatsbombGithub

  wyscout:
    type: sources.Wyscout
    configuration:
      username: !ENV ${WYSCOUT_USERNAME}
      password: !ENV ${WYSCOUT_PASSWORD}

extract_jobs:
#  - source: statsbomb
#    selectors:
#      - competition_id: 11
#        season_id: [42, 90]
  - source: wyscout
    selectors:
      - season_id: 188105
