main:
  dataset_url: sqlite:////tmp/ingestify-demo/dataset.db
  file_url: file:///tmp/ingestify-demo/data/
  default_bucket: main
#  dataset_url: teamtv://test-bucket
#  file_url: teamtv://test-bucket

sources:
  statsbomb:
    type: sources.StatsbombGithub

extract_jobs:
  - source: statsbomb
    selectors:
      - competition_id: 11
        season_id: [42, 90]
