main:
  dataset_url: !ENV ${DATABASE_URL}/ingestify
  file_url: file:///tmp/blaat2

sources:
  statsbomb:
    type: StatsbombGithub

sinks:
  postgres_warehouse:
    type: postgresql
    url: !ENV ${DATABASE_SINK_URL}



extract_jobs:
  - source: statsbomb
    selectors:
      - season_id: [21, 42]
        competition_id: 16
      - season_id: [40, 41, 42]
        competition_id: 11

load_jobs:
  - on: ["DatasetCreated", "VersionAdded"]
    filter:
      dataset_type: event
    transformer: KloppyToPandas
    target:
      sink: postgres_warehouse
      table: ${dataset.platform}_events


# "https://raw.githubusercontent.com/statsbomb/open-data/master/data/competitions.json"
