
sinks:
  postgres_warehouse:
    type: postgresql
    kwargs:
      url: !ENV ${DATABASE_SINK_URL}


load_jobs:
  - on: ["DatasetCreated", "VersionAdded"]
    filter:
      dataset_type: event
    transformer: KloppyToPandas
    target:
      sink: postgres_warehouse
      method: upsert
      kwargs:
        table_name: ${dataset.platform}_events
#  - on: ["DatasetCreated", "VersionAdded"]
#    filter:
#      dataset_type: event
#    transformer:
#      kloppy_ds = kloppy_autoload(dataset)
#    target:
#      sink: xml_storage
#      method: overwrite
#      args:
#        filename: ${dataset.identifier.match_id}.xml


# "https://raw.githubusercontent.com/statsbomb/open-data/master/data/competitions.json"
